"""Document actions (stub).

Silver tier stub — generates a basic markdown report to Plans/.
Real implementations deferred to Gold tier.
"""

import os
from datetime import datetime, timezone
from pathlib import Path


DEFAULT_VAULT_PATH = "/home/safdarayub/Documents/AI_Employee_Vault"


def generate_report(title: str = "Untitled Report", content: str = "",
                    report_type: str = "general", **kwargs) -> dict:
    """Generate a markdown report in vault Plans/ folder.

    Args:
        title: Report title
        content: Report body content
        report_type: Type of report (general, briefing, summary)

    Returns:
        dict with status, action, report_file path
    """
    vault_path = kwargs.get("vault_path",
                            os.environ.get("VAULT_PATH", DEFAULT_VAULT_PATH))
    vault_root = Path(vault_path)
    plans_dir = vault_root / "Plans"
    plans_dir.mkdir(parents=True, exist_ok=True)

    ts = datetime.now(timezone.utc)
    ts_str = ts.strftime("%Y-%m-%dT%H:%M:%S")
    ts_file = ts.strftime("%Y%m%d-%H%M%S")

    slug = title[:40].lower().replace(" ", "-").replace("/", "-")
    filename = f"report-{slug}-{ts_file}.md"
    filepath = plans_dir / filename

    report_content = f"""---
title: "{title}"
created: "{ts_str}"
type: {report_type}
source: action-executor
status: draft
---

## {title}

{content if content else "*(No content provided — stub report)*"}

---
*Generated by action-executor at {ts_str}*
"""

    # Atomic write
    tmp = filepath.with_suffix(filepath.suffix + ".tmp")
    tmp.write_text(report_content, encoding="utf-8")
    os.rename(tmp, filepath)

    return {
        "status": "generated",
        "action": "generate_report",
        "report_file": str(filepath),
        "title": title,
        "report_type": report_type,
        "detail": f"Report written to {filepath}",
        "timestamp": ts_str,
    }
