module.exports = {
  apps: [
    {
      name: "ai-employee-watcher",
      interpreter: __dirname + "/../.venv/bin/python3",
      script: "src/file_drop_watcher.py",
      cwd: __dirname + "/..",
      max_restarts: 5,
      min_uptime: 60000,
      restart_delay: 1000,
      autorestart: true,
      watch: false,
      out_file: "/home/safdarayub/Documents/AI_Employee_Vault/Logs/watcher-pm2-out.log",
      error_file: "/home/safdarayub/Documents/AI_Employee_Vault/Logs/watcher-pm2-error.log",
      env: {
        VAULT_PATH: "/home/safdarayub/Documents/AI_Employee_Vault",
        DROP_FOLDER: "/home/safdarayub/Desktop/DropForAI",
      },
    },
    {
      name: "gmail-watcher",
      interpreter: __dirname + "/../.venv/bin/python3",
      script: ".claude/skills/gmail-watcher/scripts/gmail_poll.py",
      args: "--minutes 30 --interval 120",
      cwd: __dirname + "/..",
      max_restarts: 5,
      min_uptime: 60000,
      restart_delay: 5000,
      autorestart: true,
      watch: false,
      out_file: "/home/safdarayub/Documents/AI_Employee_Vault/Logs/gmail-pm2-out.log",
      error_file: "/home/safdarayub/Documents/AI_Employee_Vault/Logs/gmail-pm2-error.log",
      env: {
        VAULT_PATH: "/home/safdarayub/Documents/AI_Employee_Vault",
        PROJECT_ROOT: __dirname + "/..",
      },
    },
    {
      name: "whatsapp-watcher",
      interpreter: __dirname + "/../.venv/bin/python3",
      script: ".claude/skills/whatsapp-watcher/scripts/whatsapp_monitor.py",
      args: "--interval 15",
      cwd: __dirname + "/..",
      max_restarts: 5,
      min_uptime: 60000,
      restart_delay: 5000,
      autorestart: true,
      watch: false,
      out_file: "/home/safdarayub/Documents/AI_Employee_Vault/Logs/whatsapp-pm2-out.log",
      error_file: "/home/safdarayub/Documents/AI_Employee_Vault/Logs/whatsapp-pm2-error.log",
      env: {
        VAULT_PATH: "/home/safdarayub/Documents/AI_Employee_Vault",
        PROJECT_ROOT: __dirname + "/..",
      },
    },
    {
      name: "scheduler-daemon",
      interpreter: __dirname + "/../.venv/bin/python3",
      script: ".claude/skills/daily-scheduler/scripts/scheduler_daemon.py",
      cwd: __dirname + "/..",
      max_restarts: 5,
      min_uptime: 60000,
      restart_delay: 5000,
      autorestart: true,
      watch: false,
      out_file: "/home/safdarayub/Documents/AI_Employee_Vault/Logs/scheduler-pm2-out.log",
      error_file: "/home/safdarayub/Documents/AI_Employee_Vault/Logs/scheduler-pm2-error.log",
      env: {
        VAULT_PATH: "/home/safdarayub/Documents/AI_Employee_Vault",
        PROJECT_ROOT: __dirname + "/..",
      },
    },
  ],
};
